filebeat.inputs:
- type: log
  enabled: true
  tags: ipb-php-logs
  fields:
    log_source: ipb-php-logs
    addr: 192.168.0.148
  paths:
    - /data/www/gmf_bms/storage/logs/*.log
    - /data/www/gmf_ipb/storage/logs/*.log
    - /data/www/gmf_oms/storage/logs/*.log
    - /data/www/gmf_rms/storage/logs/*.log
    - /data/www/gmf_utility/storage/logs/*.log
    - /data/www/xc-pms/storage/logs/*.log
    - /data/www/xc-uds/storage/logs/*.log
  multiline.pattern: '^(\d+)-(\d+)-(\d+)\s+(\d+):(\d+):(\d+)|^\[\d+-(\d+)-(\d+)\s+(\d+):(\d+):(\d+)\]|^sync start|Running scheduled command:'
  multiline.negate: true
  multiline.match: after
      
- type: log
  enabled: true
  tags: nginx-logs
  fields:
    log_source: nginx-logs
    addr: 192.168.0.148
  paths:
    - /data/logs/nginx/*.log

- type: log
  enabled: true
  tags: systems-messages
  fields:
    log_source: systems-messages
    addr: 192.168.0.148
  paths:
    - /var/log/messages
    - /var/log/cron
    - /var/log/secure
  multiline.pattern: '^[a-zA-Z]+\s+[0-9]{2}\s+[0-9]{2}:[0-9]{2}:[0-9]{2}'
  multiline.negate: true
  multiline.match: after
output.redis:
  hosts: ["192.168.10.105:6380"]
  db: 0
  timeout: 5
  password: "intel.com"
  key: "default_list"
  keys:
    - key: "systems-messages"  
      when.equals:
        fields.log_source: "systems-messages"
    - key: "nginx-logs"  
      when.equals:
        fields.log_source: "nginx-logs"
    - key: "ipb-php-logs"  
      when.equals:
        fields.log_source: "ipb-php-logs"
